apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
  labels:
    me.kundun: monitoring
spec:
  generators:
    - git:
        repoURL: https://github.com/luminosita/homelab
        revision: prometheus
        directories:
          - path: k8s/infra/monitoring/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        me.kundun: controllers
    spec:
      project: monitoring
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/luminosita/homelab
        targetRevision: prometheus
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
