apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-auth-production
  namespace: oauth2-proxy 
spec:
  issuerRef:
    name: cloudflare-cluster-issuer-production
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "auth.emisia.net"
  secretName: cert-auth-production

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  subject:
    organizations:
      - cert-manager
