apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
      namespace: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy
          imagePullPolicy: IfNotPresent
          args:
            - --provider=keycloak-oidc
            - --email-domain=*
            - --http-address=0.0.0.0:4180
            - --oidc-issuer-url=https://auth.emisia.net/realms/emisia
            - --redirect-url=https://echo.emisia.net/oauth2/callback
            - --skip-provider-button=true
            - --code-challenge-method=S256
            - --set-xauthrequest=true
            - --set-authorization-header=true
          env:
            - name: OAUTH2_PROXY_CLIENT_ID            
              valueFrom:
                secretKeyRef:
                  name: oidc-credentials
                  key: oauth2_proxy_client_id
            - name: OAUTH2_PROXY_CLIENT_SECRET       
              valueFrom:
                secretKeyRef:
                  name: oidc-credentials
                  key: oauth2_proxy_client_secret
            - name: OAUTH2_PROXY_COOKIE_SECRET      
              valueFrom:
                secretKeyRef:
                  name: oidc-credentials
                  key: oauth2_proxy_cookie_secret          
          ports:
            - containerPort: 4180
              protocol: TCP
