apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
      namespace: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy
          imagePullPolicy: IfNotPresent
          args:
            - --provider=keycloak-oidc
            # - --cookie-domain="echo.emisia.net"
            - --email-domain=*
            - --http-address=0.0.0.0:4180
            #- --proxy-prefix=/oauth2
            - --redirect-url=https://auth2.emisia.net/oauth2/callback
            - --oidc-issuer-url=https://auth.emisia.net/realms/emisia
            # - --whitelist-domain=.echo.emisia.net
            - --skip-provider-button=true
            - --upstream=file:///dev/null
            - --session-cookie-minimal=true          
          env:
            - name: OAUTH2_PROXY_CLIENT_ID            
              valueFrom:
                secretKeyRef:
                  name: oidc-credentials
                  key: oauth2_proxy_client_id
            - name: OAUTH2_PROXY_CLIENT_SECRET       
              valueFrom:
                secretKeyRef:
                  name: oidc-credentials
                  key: oauth2_proxy_client_secret
            - name: OAUTH2_PROXY_COOKIE_SECRET      
              valueFrom:
                secretKeyRef:
                  name: oidc-credentials
                  key: oauth2_proxy_cookie_secret          
          ports:
            - containerPort: 4180
              protocol: TCP
