apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
      namespace: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy
          imagePullPolicy: IfNotPresent
          args:
            - --http-address=http://:4180
            - --upstream=file:///dev/null
            - --provider=keycloak-oidc
            - --client-id=echo
            - --client-secret-file=/var/oidc/oidc.secret
            - --proxy-prefix=/oauth2
            - --redirect-url=/oauth2/callback
            - --oidc-issuer-url=https://auth.emisia.net/realms/emisia
            - --email-domain=* # Validate email domain for users, see option documentation
            - --code-challenge-method=S256 # PKCE        
            - --cookie-secret=cfsftHakFx0jmWjmKKSD73GsWi9uxOeFd9psk8ns8dg=
            - --cookie-secure=true
            - --cookie-name=_oauth2_proxy
            - --cookie-expire=24h
            - --set-xauthrequest=true
          ports:
            - containerPort: 4180
              protocol: TCP
          volumeMounts:
            - name: oidc
              mountPath: /var/oidc/
      volumes:
        - name: oidc
          secret:
            secretName: oidc-secret
