apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: true
    nginx.ingress.kubernetes.io/service-upstream: 'true'
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  ingressClassName: nginx
  tls:
    - secretName: cert-auth2-production
      hosts:
        - auth2.emisia.net
  rules:
  - host: auth2.emisia.net
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
