apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
  - collector.yaml
  - instrumentation.yaml

helmCharts:
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    version: 1.10.3
    releaseName: "tempo"
    namespace: tracing
    valuesFile: tempo-values.yaml
