persistence:
  enabled: true
  storageClassName: proxmox-csi
  accessModes:
    - ReadWriteOnce
  size: 10Gi

tempo:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  ingester:
    trace_idle_period: 10s  
    max_block_bytes: 1_000_000  
    max_block_duration: 1m  

  retention: 1h

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal