apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: auth
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/luminosita/k8s-cluster-talos'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'authelia'
      server: '*'
    - namespace: 'keycloak'
      server: '*'
    - namespace: 'lldap'
      server: '*'
    - namespace: 'oauth2-proxy'
      server: '*'
    - namespace: 'openldap'
      server: '*'
    - namespace: 'netbird'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
