---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.keycloak.clientSecret: AgCrgigP8EL4XCtbFH8GHpmkfbTaJ8IWuRDajP/9TGoxUaTt/lIOEXvsP5VpHb+n1ktz+Cy7Smpkpske7nyfiBxfEqriqukuRaytH0NAk3FohERJVDrM3Zj4Rzw6rd2269k7N5JeKGbKkzaMHsUdWjUIP1b2KFxQv9/h++h1AFREHbe7JBQ8j//2weEcxX9PDSBBeaAnm0NPeVUzzKrw+WCBW+rsJ8JqgV0WlMTYd5YE0rqPkl1oA24kKnDzfCDe1IPYQTr3NcM1iFveyJZCQ4eGAyQpXkhEyxeQTbZYCzY0pqlzh9uyb8Z+Fj3glnilQqqhZIiOiV3aODyVvIYcOwufRiTHER90eFge2KXhn88Fy8V2Vi9zsPJHcGj+jxg0LNE6KlSX7BxK5MzPlfC77rdSk8eL71fiH6Ye+wE8EbYTKpKu7b1oKCJy3/k1ZCJNGtKVvsDzF+ybdpeDNPnbvT98GYU+RImK+hfYaatoj2Ndtn3DEhFpx7A47UrW15Qc699nnN8pyW4IYS5TRSAYBjKZ5Qlh4fEmQLPJQJi4GE0wqHn8h4oztyIEWYopd8iA4fqN9iHtSI/FkL32tpRNzoOjygoR8DDqB0VuzRyMP2/XGee7opm/6k53sYVIVySxe8NxFm23Btt2YByaFQB5dCLjLzwb0fCUxBXOB3l/3OFG364njq5bHLLbFV0WbowqihYA/A3KX0Du97y6YEcoOjlXt8jmpfCW34cugMKOrd9l4g==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
