---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.keycloak.clientSecret: AgB71VWHMdJYMeydPLgQhLQSNONDky94P5RodUDT4zcXvIi+BzMLhvDzxYjanUR+QnuFKSyKdgxvFDVjqZo10jWeNTPJtE3FQIaVEzYEhzR7ETngGl+lB+xktajvx5P0w45A1tqoCiqJFGntzGflztdHhBEgIomUuYep1Mrd+4Y1am7XKcGb8gT1CleFRCc6fTb1UGgAjRAamcK9d0hK9TtlZvllMz0+5Ngx9/VlKclkYhYpXSvyEGU5wqwECM6QVP7u/k7fxk7+FxA+r52SsdpwM3grO3rO3vVkyCLN7GOVZSE3Qd2hhoyb9JKmYAAaJM//hMEbmc6FcJV0oE2Owmhg+dE8Wi4OqBIOfCJXczUmdA3ZN1GG6oJk1l7vqdg209AgEkIkm6rv/iy0JaN/gtQrd94je45TykW4ysuRDy+IC7m0BQdwdqYdN+qLIIziO5T97TiDrNz3qSkd0RbYPWcOCKMMFxSWVy8kRIoMLcwwmrBbaOJtFfer+oOvfO0mBvoidodsHtgaU86QhfhMSD3cWblNudMLndWfxk9XBL1oYs4L4cZM0eSYWb0gDscF/J5NWxijdzuQvryHAXPLOqb2K0HG40VQzoGyEFZzxloBZtuXKRNcayejsHTqjUPQjIplppI7PjibgW5f+FlHPp6xq/8PWn52aDcxLkUEXU90niZBYEcceM0nb8feMVAEua7H3IaUA6GiNayNDp0HiJy9HfYzxe3dtczNI5TWEMFY2Q==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
