apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - http-route.yaml
  - https-route.yaml
  - argocd-credentials.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 7.4.5
    releaseName: "argocd"
    namespace: argocd-system
    valuesFile: values.yaml
