---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    metadata:
      namespace: docker
      labels:
        app: docker
    spec:
      containers:
        - name: docker
          image: docker:latest
          imagePullPolicy: Always
