---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      namespace: docker
      labels:
        app: docker
    spec:
      containers:
        - name: docker
          image: docker:dind
          imagePullPolicy: Always
