---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      namespace: docker
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: ["sleep"]
          args: ["infinity"]
          imagePullPolicy: Always
