apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - pvc.yaml
  - pod.yaml
  - bootstrap.yaml
  - deployment.yaml
  - svc.yaml
  - http-route.yaml
  - https-route.yaml
