apiVersion: v1
kind: Pod
metadata:
  name: gollum-pod-debug
  namespace: gollum
spec:
    restartPolicy: OnFailure
    containers:
      - name: init-clone-repo
        image: alpine/git
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        # args:
        #   - clone
        #   - '--single-branch'
        #   - '--'
        #   - 'https://https://github.com/luminosita/wiki'
        #   - '/wiki/'
        # env:
        # - name: GIT_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       key: username
        #       name: test-secret
        # - name: GIT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       key: password
        #       name: test-secret
        # resources: {}
        # terminationMessagePath: /dev/termination-log
        # terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /wiki
            name: gollum-repo
    volumes:
      - name: gollum-repo
        persistentVolumeClaim:
          claimName: pvc-gollum

