apiVersion: v1
kind: Pod
metadata:
  name: gollum-pod-debug
  namespace: gollum
  labels:
    app.kubernetes.io/name: gollumic
spec:
  securityContext:
    runAsNonRoot: false
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: gollum-pod-debug
      image: gollumwiki/gollum:latest
      args: ["--page-file-dir /wiki/repo"]      
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: [ "ALL" ]
      volumeMounts:
        - name: gollum-repo
          mountPath: /wiki
  restartPolicy: OnFailure
  volumes:
    - name: gollum-repo
      persistentVolumeClaim:
        claimName: pvc-gollum

