apiVersion: v1
kind: Service
metadata:
  name: gollum
  namespace: gollum
spec:
  selector:
    app.kubernetes.io/name: gollumic
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
