apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  me.kundun: crossplane-crds
  app.kubernetes.io/managed-by: argocd

resources:
  - project.yaml
  - application-set.yaml
