apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: argocd
      me.kundun: crossplane-crds

resources:
  - project.yaml
  - application-set.yaml
