apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: nginx-ingress
    repo: https://helm.nginx.com/stable
    version: 1.4.0
    releaseName: "nginx-ingress"
    namespace: nginx-ingress
    valuesFile: values.yaml
