apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: ingress-nginx/ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.11.2
    releaseName: "nginx-ingress"
    namespace: nginx-ingress
    
    valuesFile: values.yaml
