apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: single-lldap
  namespace: lldap
spec:
  instances: 1
  affinity:
    nodeSelector:
      topology.kubernetes.io/zone: proxmox
  managed:
    services:
      disabledDefaultServices: [ "ro", "r" ]
  storage:
    size: 50M
    pvcTemplate:
      storageClassName: proxmox-csi
      volumeName: pv-lldap
      accessModes:
        - ReadWriteOnce
  bootstrap:
    initdb:
      database: lldap
      owner: lldap
      secret:
        name: single-lldap-app