apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  namespace: lldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: lldap
      labels:
        app: lldap
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: proxmox
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: lldap
          image: nitnelave/lldap:latest-debian
          command: ["sleep"]
          args: ["infinity"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
          env:
            - name: LLDAP_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: jdbc-uri
                  name: single-lldap-app
          envFrom:
            - configMapRef:
                name: common-env
            - secretRef:
                name: lldap-credentials
          ports:
            - name: ldap
              containerPort: 3890
            - name: ldaps
              containerPort: 6360
            - name: web
              containerPort: 17170
          volumeMounts:
              - name: lldap-data
                mountPath: /data
                # mountPath: /data/lldap_config.toml
                # subPath: lldap_config.toml
      volumes:
        - name: lldap-data
          emptyDir: { }
          # configMap:
          #   name: config-toml
