apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: common-env
    namespace: lldap
    literals:
      - TZ="Europe/Oslo"
      - GID="1001"
      - UID="1001"
  - name: bootstrap-env
    namespace: lldap
    literals:
      - LLDAP_URL="http://lldap:80"   
      - LLDAP_ADMIN_USERNAME="admin"
      - DO_CLEANUP="true"     
  - name: config-toml
    namespace: lldap
    files:
      - lldap-config.toml

resources:
  - ns.yaml
  - cnpg-config.yaml
  - cnpg.yaml
  - svc.yaml
  - lldap-credentials.yaml
  - lldap-config.yaml
  - deployment.yaml
  - local-route.yaml
  - bootstrap.yaml
