apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    me.kundun: infrastructure
spec:
  generators:
    - git:
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        revision: cnpg
        directories:
          - path: k8s/infra/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        me.kundun: infrastructure
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        targetRevision: cnpg
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
