---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-credentials
  namespace: mariadb
spec:
  encryptedData:
    password: AgBKcoUF0xjkyQLFI13Z7SBXCfy02UVfALpR0uRFSKE68HTBVuk6rWazRCw/MxziAH9XsK0im1DSl8dl1CEKYgqzCyjbfN5RsKkBj4BNShiJ1V4uf0RjS/aApInvwYyokn5ZVJERnSCRTMKu0bDYSDOwAS7JRBistBQdUpoJcadDivtZlt7Kg71BEZXlhLr+VsdyRIcNdebeiIzo6x2YHAzZ39FJ5KVqKMZID20gTxTzI3PfC4elhFoUTmKgo/jWTWWLlY5Ryxp2YsnXlN1AK0dTsNr/V5WGeADClCKL0HMVqdOMrT07OgXUxRWxp63KBtx1dZVhuBX5ry+X5G4GozQ2BEPFRNXDZAkdnmoZuaYaKKYo3NQwKfzW6MoUqscWmLdEy669AoPsxzp/ZA6dcvxivDgW8nfmb24UFzRl9CkXZifzUykpyw4FXTiQxi5Gd0TdJpjXHoStD08578sUEbPaCO8r0+xQOnyDTc761XG7lXmryuBOyM3c95eGIQ1CnRTIbV5fLbelX/Zjg7pfA/dFVDeYE6EcKY6CkW+8UpT90Y1dMayLggB3PDYq9dAwotCfxKOb1a92E02UFe2+SEzM25lN4UUvjv22vgkIXFF+CdzaCYG7ZFAEjBjBhr9nd1lOMQy5bsdKQGhSWLzSToVhoxCdTFVBXEWep4FSIKnG6eohIjh49O9Wx+nINs3I1aVqu2z1W5q5ww==
    root-password: AgAlOXcBcOr2HlL4TQlHVz+b8pMERAODkwGlDLT+ykiWJCKN4A/0e9nC83tMaQBnIuATxpDFQh/qyVvbGruOek317VM8Qh3C6vh6Pzl5zE6Q3be40OvL/km7PO3Q9jE1dT0t3XQ/F4fWfHZlxAWsozJbl9ybCetLMUjXkfpJQQuQ7Kdh5G5lSb0bTlgCdbqz+sx34PDxq3Rng84S4cbwrXPnyXI/a++FdXtJcmh1p1lWNOk1hRT6aCzOTcojgH+AUg60gcIUd+MhUaZKISzrx3TYOMNIeBwZ4CzysuQTVdDPBH/gB40tWYi6C6KIr5XAxucV4Vp8GdetCIkSQIB5NUKzA8RS8qAPxoktegoCLr0u6/e7PaNieLsRTzb85w1ml/xVgKx82dk51CvxDof/YLp4YGrG8Bit/YV18exGJBnu6t9IcFJoEmfpvpVBy4bYwnMck21J7wWjTIpDj2AHsKZU5FW27fbWUaUVmLcRg0yQilGPQsSP+PokHMkMMba3jk8ct6C7vYkZL5YWxw1/JBaVw5frkKD2p9a2X3SsIO1WSHSl4u+HnJ8u9YCX8s+niNevCgB8Di8dPtA285uuA1GVu6T7PvL1tt8oW+9YWSCsCTQXtxmw++H3zQn3cJyU05lXlxBYRK4UoLKFEiVAH3IEZP852ZlREDTgR6FjPM9ZavdXqUOA1CHu9zct1eBQ00VzqKcv6B8tVw==
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-credentials
      namespace: mariadb
