---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb
  namespace: mariadb
spec:
  storageClassName: proxmox-csi
  volumeName: pv-mariadb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
