apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  me.kundun: monitoring
  app.kubernetes.io/managed-by: argocd

resources:
  - pve-credentials.yaml
  - deployment.yaml
  - svc.yaml
  - scrape-config.yaml
