apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: static-config
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  staticConfigs:
    - labels:
        job: prometheus
      targets:
        - exporter-proxmox.monitoring.svc.cluster.local:9221
  metricsPath: /pve
  params:
    target:
      - proxmox.lan
    module: [default]
    cluster: ['1']
    node: ['1']