apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-emisia-test
  namespace: gateway
spec:
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - emisia.net
    - test.emisia.net
  secretName: cert-emisia

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  subject:
    organizations:
      - cert-manager
