apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-emisia
  namespace: gateway
spec:
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - emisia.net
    - "*.emisia.net" # ✅ Copied from the `hostname` field.
  secretName: cert-emisia