apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - gateway-class.yaml
  #- cert-emisia-wildcard-staging.yaml
  - cert-emisia-wildcard-production.yaml
  #- gw-internal-staging.yaml
  - gw-internal-production.yaml
  - gw-tls-passthrough.yaml
  - gw-insecure.yaml
  