apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-emisia.yaml
  - cert-emisia-wild.yaml
  - cert-emisia-test.yaml
  - gateway-class.yaml
  - ns.yaml
  - gw-external.yaml
  - gw-internal.yaml
  - gw-tls-passthrough.yaml
  - gw-insecure.yaml
  