apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: internal
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/luminosita/k8s-cluster-talos'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'wikijs'
      server: '*'
    - namespace: 'android'
      server: '*'
    - namespace: 'ejabberd'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'