apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: single-matterhorn
  namespace: cnpg-database
spec:
  instances: 1
  affinity:
    nodeSelector:
      topology.kubernetes.io/zone: proxmox
  managed:
    services:
      disabledDefaultServices: [ "ro", "r" ]
      additional:
        - selectorType: rw
          updateStrategy: patch
  storage:
    size: 5G
    pvcTemplate:
      storageClassName: proxmox-csi
      volumeName: pv-matterhorn
      accessModes:
        - ReadWriteOnce
  bootstrap:
    initdb:
      database: matterhorn
      owner: matterhorn