apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: lua
    namespace: haproxy
    files:
      - http.lua
      - auth-request.lua
      - json.lua

resources:
  - ns.yaml

helmCharts:
  - name: kubernetes-ingress
    repo: https://haproxytech.github.io/helm-charts
    version: 1.41.0
    releaseName: "haproxy"
    namespace: haproxy
    valuesFile: values.yaml
