apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ns.yaml

helmCharts:
  - name: kubernetes-ingress
    repo: https://haproxytech.github.io/helm-charts
    version: 1.41.0
    releaseName: "haproxy"
    namespace: haproxy
    valuesFile: values.yaml
