controller:
  service:
    enabled: true
    type: LoadBalancer
    annotations: 
      io.cilium/lb-ipam-ips: "192.168.50.225" # Static IP Assignment

  kubernetesGateway:
    enabled: true
    gatewayControllerName: haproxy.org/gateway-controller
