apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testlab-tyk
  namespace: argocd
  labels:
    me.kundun: testlab-tyk
spec:
  generators:
    - git:
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        revision: tyk
        directories:
          - path: k8s/testlab/*
          - path: k8s/testlab/tyk
            exclude: true
  template:
    metadata:
      name: '{{ path.basename }}-test'
      labels:
        me.kundun: testlab-tyk
      finalizers:
    spec:
      project: testlab-tyk
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        targetRevision: tyk
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: tyk
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true