apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testlab-mariadb
  namespace: argocd
  labels:
    me.kundun: testlab-mariadb
spec:
  generators:
    - git:
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        revision: mariadb
        directories:
          - path: k8s/testlab/*
  template:
    metadata:
      name: '{{ path.basename }}-test'
      labels:
        me.kundun: testlab-mariadb
      finalizers:
    spec:
      project: testlab-mariadb
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        targetRevision: mariadb
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
#          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
