apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-test
  namespace: argocd
  labels:
    me.kundun: testlab-nexus
  finalizers:
spec:
  project: testlab-nexus
  source:
    plugin:
      name: kustomize-build-with-helm
    repoURL: https://github.com/luminosita/k8s-cluster-talos
    targetRevision: nexus
    path: k8s/testlab/nexus
  destination:
    name: in-cluster
    namespace: nexus
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
