apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testlab
  namespace: argocd
  labels:
    me.kundun: testlab
spec:
  generators:
    - git:
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        revision: authelia
        directories:
          - path: k8s/testlab/*
          - path: k8s/testlab/solar-system
            exclude: true
          - path: k8s/testlab/caddy
            exclude: true
  template:
    metadata:
      name: '{{ path.basename }}-test'
      labels:
        me.kundun: testlab
      finalizers:
    spec:
      project: testlab
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        targetRevision: authelia
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
