apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testlab-mariadb
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/luminosita/k8s-cluster-talos'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'mariadb'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
