apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev
  namespace: argocd
  labels:
    me.kundun: dev
spec:
  generators:
    - git:
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        revision: HEAD
        directories:
          - path: k8s/apps/dev/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        me.kundun: dev
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: dev
      source:
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true