apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  sourceRepos:
    - '{{ env GLOBAL_REPO_URL }}'
#    - 'https://github.com/luminosita/k8s-cluster-talos'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'unrar'
      server: '*'
    - namespace: 'whoami'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'