---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAAhH5vCSxrLkGub9Ubm+jxjLM0GsHDPl1CYGuQ5ph4Gq1eUSPGfvaDnvGoqWOBmV3PzhmlBssPed2JFkVFE83LztwjWeOG9p5rFtQxqq09JqcyuuTydffu78rgw10bs3bFzdYl1HMoRJy/MviO1M3bautEXi0fYxn7TyZKi0v4YAhBO2dWqOgz9+DxIOEozElldncoBePYpEAD0LrlxegQ8W3I4GtFQ+m7ZVd+Xc6ja9iFZyqAUvtFiRHaLsxbXCmpcKFX5n1r/aBMs1Hr8W03ss/Zy8I2i0fUnR+L2B36tyEBAVdMZyiQ+v7b/g4g+eAVO3rNC7XObvbltPebW19E99zE6q5wGqPqIWUBFibJ/JRMUR1wc0v010QxQwKzeHJsn5TEiYZv+JKGRn8Hu0xNcpRZNpXKtM5kgZAfGczct8qV8rDnyd8v+u7u27fnU5Nd8BITDXg78ya/vj3bqT8Z+SD/78LgqJAiSXfmmmKWsaxp/ejjFtUT2mI38JpTzKSwBxs7OH0PfgB58VZL21hHriwgtuWV6YqJ0Asl16xtJPL2nggJ+iztfO0Bb4MPQRiUNcc5BqSbGvp1fM/+yerlnP9dvXGlzlCzTc36r0QmnFVtu+fyjCy62OmElEKzpvv0+OOOEl1l2U3jZKiZIVuCkIU8hlT6ABrkB/wFJ534EUKTkcfoH0QDxW4rtiXrS14FwsSJs5bagoTYi+d2ODI8/xAtXQPweI5bLYRHvZFHpqVaX1AkRACP
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
