# gateway/cloudflare-api-token.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
#cert-token
  api-token: G00tXwhzWrIGtqC6CNc7YG477pWf9xKmvvNnmTa2   
  #cert-mananger token
  # api-token: gxqpNkHwwhbPgZhU70QeseYBblQR48SZFAiCx1UD     #TODO Change to sealed secret
