apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB1MdN1H9VMSNg3/Htvpp+Hp/b7mpEFCRlwUVbyPiRg7IQNn59qKGa57MymtUPtQCeY7YjiumpwOlpObizSJEwOGYT22LzUtOrvOv6qW3RbU+6iSKA118tRxDCJB8KwDtzHJTCNB9ooSbrdMYYs17iQSu71VpeeeUEI5KbMLWIV0NAazbtprFLuU3wgJtNxlwFj/XWmJb+d0Q9t92R+y31qogveRfzVyBxNsWBh9uaYXc+p3WXSX1mvDkpxUnx23Ss5hWPqdr8bZwO0mMDx+38Fvh/29zRDC3i8ZMATQzIZKojn44Kmd1wEMQ7PN7z4y8iA4Yh4vOwVN8R1P6Xxo/pC6CcTCtGj/ppZPnhLOR3wwTNF0+gYiUxPYhPh61aldF3CAyrbUJ/97P3/uA8OBMZoNQLPtONLy3R1+Sa+DwatdGqZIs2ByeYPOzdQGcPtbxX1Ez083wu5//SQWcTb/L4oj2dHBGC/aR2Zn7tCi6GA91HKjmy6nDI0FxY3gKEQcfRuNwd4mQShBZ5EVEHg2nm0sSCTzfqHMZeQBuShrSCaMnNTVvfSVxskPdUVwCzL4kFaRnOMfXw4vJ+Y9btf77ukAXp0vonlR8ZoS9Q2+PTAbfwrr4hFy5niVs/Nn4taZXzKkFty6Ol+ofEAgZpSm/YfkTGi9fEN/4BsXH6UWSqftKI7QA4HXyqpx+DXYNRspnu+2o4HnplhJJjVnjiiJ6cXoX3SCevdOdnQV3HiMHHGYNUgPiBBDpKR
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
