apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external
  namespace: argocd
  labels:
    me.kundun: external
spec:
  generators:
    - git:
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        directories:
          - path: k8s/apps/external/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        me.kundun: application
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: external
      source:
        repoURL: https://github.com/luminosita/k8s-cluster-talos
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true