apiVersion: cert-manager.io/v1  
kind: Certificate  
metadata:  
  name: ejabberd-ca-certificate
  namespace: ejabberd  
spec:  
  issuerRef:  
    name: selfsigned-cluster-issuer  
    kind: ClusterIssuer  
    group: cert-manager.io
  secretName: ejabberd-ca-certificate
 
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: true  
  commonName: "xmpp-server.com"  
  
  subject:  
    organizations:  
      - ACME Inc.  
    organizationalUnits:  
      - Chat  
 
  additionalOutputFormats:
    - type: CombinedPEM
    - type: DER
