apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - pvc.yaml
  - keycloak-admin.yaml
  - keycloak-db-credentials.yaml
  - http-route.yaml
  - https-route.yaml

helmCharts:
  - name: keycloak
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: keycloak
    namespace: keycloak
    version: 22.1.3
    valuesFile: values.yaml
