apiVersion: v1
kind: Service
metadata:
  name: sun
  namespace: cf-solar
spec:
  type: ClusterIP
  selector:
    app: sun
  ports:
    - name: web
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: moon
  namespace: cf-solar
spec:
  type: ClusterIP
  selector:
    app: moon
  ports:
    - name: web
      port: 80
      targetPort: 8080
