apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  me.kundun: auth
  app.kubernetes.io/managed-by: argocd

resources:
  - ns.yaml
  - project.yaml
  - application-set.yaml
