apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - cloudflare-credentials.yaml
  - https://github.com/adyanth/cloudflare-operator/config/default
  - cluster-tunnel.yaml


  