apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/experimental-install.yaml
#  Using slightly older CRDs for HAProxy compatibility
#  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.5.1/experimental-install.yaml