apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: caddy-system

resources:
  - ns.yaml 

helmCharts:
  - name: caddy-ingress-controller
    repo: https://caddyserver.github.io/ingress/
    releaseName: mycaddy
    namespace: caddy-system
    version: 1.1.0
    valuesFile: values.yaml
