apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  namespace: openldap
  labels:
    app: ldap
spec:
  selector:
    matchLabels:
      app: ldap
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap
          image: osixia/openldap:1.5.0
          args: ["--copy-service", "--loglevel", "debug"]
          volumeMounts:
            - name: config
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom/config-ldap.ldif
              subPath: config-ldap.ldif
          ports:
            - containerPort: 389
              name: openldap
          env:
            - name: LDAP_TLS_VERIFY_CLIENT
              value: "try"
            - name: LDAP_ORGANISATION 
              value: "Emisia"
            - name: LDAP_DOMAIN 
              value: "emisia.net"
          #   - name: LDAP_BACKEND 
          #     value: "hdb"
          #   - name: LDAP_TLS 
          #     value: true
          #   - name: LDAP_TLS_ENFORCE 
          #     value: false
          #   - name: LDAP_REMOVE_CONFIG_AFTER_SETUP 
          #     value: true
          #   - name: LDAP_READONLY_USER 
          #     value: true
          #   - name: LDAP_READONLY_USER_USERNAME 
          #     value: "readonly"
          #   - name: LDAP_READONLY_USER_MASSWORD 
          #     value: "password"
          #   - name: LDAP_ADMIN_PASSWORD
          #     value: "laptop01"
          #   - name: LDAP_CONFIG_PASSWORD
          #     value: "laptop01"
      volumes:
        - name: config
          configMap:
            name: config