apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: phpldapadmin-http
  namespace: openldap
spec:
  parentRefs:
    - name: insecure
      namespace: gateway
  hostnames:
    - phpldapadmin.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: phpldapadmin
          port: 80