---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openldap-credentials
  namespace: openldap
spec:
  encryptedData:
    LDAP_ADMIN_PASSWORD: AgA017cG5m4bDjy5ZRdhrvlgjbHcVjx1eFg02LRoD7ptBFbRTVokc+9M0OkmOWmHasDuB4xaNcmNvRN4NRibXNEA0cNX3HZJ4F1BJTm8jhYW9Q4OTPRHQN6sgDoURajX+hLxSQPEXvqeb7vqgYzCPisig/rzAGASjQvo3a0ek39xBWqeFgt7A3DR0Z3XwpsHDjFLK4wMLFP5+z5LwVw9Dp9ck0Pf2bAnT/KdWMGB0JwucrH3JlF/ykiUod3PLxI3IO1pyYt8rjkzy4uLHUkp0YV6RBR5VCpBQdP0S9HCqu/Fuqwso0Rv1uyjZAWDW9yTMy5cUdinPAsBgcSx93r1kuxwHnTXgPQ9c09ki6tsNf44N7dSfKRZDqG7u97zV4IHNn2v79dazyK3JT7SKM4MJAFIeKFhhftqb6MtweAnBpdq5Eej+uC8IxH6/6tK6CJVrf+lBV/ppDkgUGGk8pSP5Y79v6gtE00qnF9iwrkeE10kafRsmDbxuys6J5XNF2Rj5VLqum7gae4OFWDlQ+94HEXjRCCQtc+vssOJ9Txt/e8Iv8yfp98WPiX6xON/iw8rXqJlV5XY0dUXCxSMbDc3CaX8rJv5xRJf2ArQ1WbuM5y/IwvF8rgU2cnwrz8s8MB604RaaVuNggJulUO2MrOerexvj6dt8aMXziu0DtO6jylvFKbeppKntq6kFKraLGq+w2o=
  template:
    metadata:
      creationTimestamp: null
      name: openldap-credentials
      namespace: openldap
