apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  namespace: openldap
  labels:
    app: phpldapadmin
spec:
  selector:
    matchLabels:
      app: phpldapadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
        - name: phpldapadmin
          image: osixia/phpldapadmin:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PHPLDAPADMIN_LDAP_HOSTS
              value: "openldap-svc.openldap"
            - name: PHPLDAPADMIN_HTTPS
              value: "false"
