apiVersion: cert-manager.io/v1  
kind: Certificate  
metadata:  
  name: ejabberd-ca-certificate
  namespace: ejabberd  
spec:  
  isCA: true  
  commonName: ca-certificate  
  subject:  
    organizations:  
      - ACME Inc.  
    organizationalUnits:  
      - Chat  
  additionalOutputFormats:
    - type: CombinedPEM
    - type: DER
  secretName: ejabberd-ca-certificate
  privateKey:  
    algorithm: ECDSA  
    size: 256  
  issuerRef:  
    name: selfsigned-cluster-issuer  
    kind: ClusterIssuer  
    group: cert-manager.io