apiVersion: v1
data:
  access-rules.yml: |-
    access_rules:
      announce:
        allow: admin
      c2s:
        allow: all
        deny: blocked
      configure:
        allow: admin
      local:
        allow: local
      muc_create:
        allow: local
      pubsub_createnode:
        allow: local
      trusted_network:
        allow: loopback
  acl.yml: |-
    acl:
      local:
        user_regexp: ""
      loopback:
        ip:
        - 127.0.0.0/8
        - ::1/128
  api-permissions.yml: |-
    api_permissions:
      admin access:
        what:
        - '*'
        - '!stop'
        - '!start'
        who:
          access:
            allow:
            - acl: loopback
            - acl: admin
          oauth:
            access:
              allow:
              - acl: loopback
              - acl: admin
            scope: ejabberd:admin
      console commands:
        from:
        - ejabberd_ctl
        - mod_http_api
        what: '*'
        who: all
      public commands:
        what:
        - status
        - connected_users_number
        who:
          ip: 127.0.0.1/8
  ejabberd.yml: |-
    hosts:
      - xmpp-server.com
    acme:
      auto: false
    ca_file: /opt/ejabberd/cacert/ca.crt
    certfiles:
      - /opt/ejabberd/certs/ejabberd-server-certificate/*.pem
    loglevel: info

    define_macro:
      TLS_CIPHERS: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256
      TLS_OPTIONS:
      - no_sslv3
      - no_tlsv1
      - no_tlsv1_1
      - cipher_server_preference
      - no_compression
    c2s_ciphers: TLS_CIPHERS
    c2s_protocol_options: TLS_OPTIONS
    s2s_ciphers: TLS_CIPHERS
    s2s_protocol_options: TLS_OPTIONS
    s2s_use_starttls: optional

    listen:
      -
        port: 5281
        transport: "tcp"
        ip: '127.0.0.1'
        module: ejabberd_http
        request_handlers:
          /api: mod_http_api
      -
        port: 5222
        transport: "tcp"
        access: c2s
        ip: '::'
        max_stanza_size: 262144
        module: ejabberd_c2s
        shaper: c2s_shaper
        starttls_required: true
      -
        port: 5280
        transport: "tcp"
        ip: '::'
        module: ejabberd_http
        request_handlers:
          /admin: ejabberd_web_admin
          /api: mod_http_api
          /bosh: mod_bosh
          /captcha: ejabberd_captcha
          /upload: mod_http_upload
          /ws: ejabberd_http_ws
      -
        port: 5443
        transport: "tcp"
        ip: '::'
        module: ejabberd_http
        protocol_options: TLS_OPTIONS
        request_handlers:
          /admin: ejabberd_web_admin
          /api: mod_http_api
          /bosh: mod_bosh
          /captcha: ejabberd_captcha
          /upload: mod_http_upload
          /ws: ejabberd_http_ws
        tls: true
      -
        port: 5269
        transport: "tcp"
        ip: '::'
        module: ejabberd_s2s_in
      -
        port: 3478
        transport: "udp"
        ip: '::'
        module: ejabberd_stun
        use_turn: false
    acl:
      admin:
        - user: admin@xmpp-server.com
      local:
        user_regexp: ""
      loopback:
        ip:
          - 127.0.0.0/8
          - ::1/128
      
    access_rules:
      local:
        allow: local
      c2s:
        deny: blocked
        allow: all
      announce:
        allow: admin
      configure:
        allow: admin
      muc_create:
        allow: local
      pubsub_createnode:
        allow: local
      trusted_network:
        allow: loopback
      
    include_config_file:
      - /opt/ejabberd/conf/api-permissions.yml
    shaper:
      normal:
        rate: 3000
        burst_size: 20000
      fast: 200000
      
    shaper_rules:
      max_user_sessions: 10
      max_user_offline_messages:
        5000: admin
        100: all
      c2s_shaper:
        none: admin
        normal: all
      s2s_shaper: fast
      
    default_db: "sql"
    new_sql_schema: "false"
    update_sql_schema: "true"
    # include_config_file:
    #   - /opt/ejabberd/db-config.yml
    modules:
      mod_adhoc: {}
      mod_admin_extra: {}
      mod_announce:
        access: announce
      mod_avatar: {}
      mod_blocking: {}
      mod_bosh: {}
      mod_caps: {}
      mod_carboncopy: {}
      mod_client_state: {}
      mod_configure: {}
      mod_disco: {}
      mod_fail2ban: {}
      mod_http_api: {}
      mod_http_upload:
        custom_headers:
          Access-Control-Allow-Headers: Content-Type
          Access-Control-Allow-Methods: GET,HEAD,PUT,OPTIONS
          Access-Control-Allow-Origin: https://@HOST@
        put_url: https://@HOST@:5443/upload
      mod_last: {}
      mod_mam:
        assume_mam_usage: true
        default: always
      mod_muc:
        access:
        - allow
        access_admin:
        - allow: admin
        access_create: muc_create
        access_mam:
        - allow
        access_persistent: muc_create
        default_room_options:
          mam: true
      mod_muc_admin: {}
      mod_offline:
        access_max_user_messages: max_user_offline_messages
      mod_ping: {}
      mod_privacy: {}
      mod_private: {}
      mod_proxy65:
        access: local
        max_connections: 5
      mod_pubsub:
        access_createnode: pubsub_createnode
        force_node_config:
          storage:bookmarks:
            access_model: whitelist
        plugins:
        - flat
        - pep
      mod_push: {}
      mod_push_keepalive: {}
      mod_register:
        ip_access: trusted_network
      mod_roster:
        versioning: true
      mod_s2s_dialback: {}
      mod_shared_roster: {}
      mod_stream_mgmt:
        resend_on_timeout: if_offline
      mod_stun_disco: {}
      mod_vcard: {}
      mod_vcard_xupdate: {}
      mod_version:
        show_os: false
  inetrc: |-
    {lookup,["file","native"]}.
    {host,{127,0,0,1}, ["localhost","hostalias"]}.
    {file, resolv, "/etc/resolv.conf"}.
  shaper-rules.yml: |-
    shaper_rules:
      c2s_shaper:
        none: admin
        normal: all
      max_user_offline_messages:
        "100": all
        "5000": admin
      max_user_sessions: 10
      s2s_shaper: fast
  shaper.yml: |-
    shaper:
      fast: 100000
      normal:
        burst_size: 20000
        rate: 3000
kind: ConfigMap
metadata:
  name: ejabberd-config
  namespace: ejabberd