apiVersion: v1
kind: ServiceAccount
metadata:
  name: ejabberd
  namespace: ejabberd
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leases
  namespace: ejabberd
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - watch
      - list
      - update
      - create

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: ejabberd
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
      - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    argocd.argoproj.io/instance: ejabberd-test
  name: ejabberd-read-pods
  namespace: ejabberd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: ejabberd
    namespace: ejabberd

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ejabberd-update-leases
  namespace: ejabberd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leases
subjects:
  - kind: ServiceAccount
    name: ejabberd
    namespace: ejabberd




