apiVersion: cert-manager.io/v1  
kind: Certificate  
metadata:  
  name: ejabberd-server-certificate  
  namespace: ejabberd
spec:  
  issuerRef:  
    name: ejabberd-issuer 
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:  
    - "xmpp-server.com"  
    - "*.xmpp-server.com"  
  secretName: ejabberd-server-certificate

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false  
  usages:  
    - server auth  
    - client auth  


  subject:
    organizations:
      - cert-manager

  additionalOutputFormats:
    - type: CombinedPEM
    - type: DER
