hosts:
  - xmpp-server.com

listenGlobal:
  # -- c2s top-level listener options:
  #    https://docs.ejabberd.im/admin/configuration/toplevel/#c2s-cafile
  #c2s_ciphers: TLS_CIPHERS
  #c2s_protocol_options: TLS_OPTIONS
  # -- s2s top-level listener options:
  #    https://docs.ejabberd.im/admin/configuration/toplevel/#s2s-access
  #s2s_ciphers: TLS_CIPHERS
  #s2s_protocol_options: TLS_OPTIONS
  s2s_use_starttls: optional

#
# https://docs.ejabberd.im/admin/configuration/toplevel/#acl
#
acl: 
  admin:
    user:
      - "admin@xmpp-server.com"  
# local:
  #   user_regexp: ""
  # loopback:
  #   ip:
  #     - 127.0.0.0/8
  #     - ::1/128
certFiles:
  # -- Please specify your kubernetes secret containing the tls certificates for
  # the domains specified in .Values.hosts, otherwise the service will not work
  secretName: {}
