namespaceOverride: "ejabberd"

statefulSet:
  # -- Number of pods of the statefulSet
  replicas: 3

hosts:
  - xmpp-server.com

listenGlobal:
  s2s_use_starttls: optional

acl: |
  admin:
    user:
      - "admin@xmpp-server.com"  
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128

accessRules: |
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

apiPermissions: | 
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          - acl: loopback
          - acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number

shaper: |
  normal:
    rate: 3000
    burst_size: 20000
  fast: 200000

shaperRules: |
  max_user_sessions: 10
  max_user_offline_messages:
    5000: admin
    100: all
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

cacert:
  secretName: ejabberd-ca-certificate
certFiles:
  # -- Please specify your kubernetes secret containing the tls certificates for
  # the domains specified in .Values.hosts, otherwise the service will not work
  secretName: 
    - ejabberd-server-certificate

elector:
  enabled: true
  createRbac: true
  name: "ejabberd"
  url: "127.0.0.1:4040"

listen:
  http:
    enabled: true
    port: 5280
    expose: true
    exposedPort: 5280
    protocol: TCP
    options:
      ip: "::"
      module: ejabberd_http
      request_handlers: 
        /admin: ejabberd_web_admin
        /api: mod_http_api
        /bosh: mod_bosh
        /captcha: ejabberd_captcha
        /upload: mod_http_upload
        /ws: ejabberd_http_ws
  https:
    enabled: true
    port: 5443
    expose: true
    exposedPort: 5443
    protocol: TCP
    options:
      ip: "::"
      module: ejabberd_http
      tls: true
      protocol_options: 'TLS_OPTIONS'
      request_handlers: 
        /admin: ejabberd_web_admin
        /api: mod_http_api
        /bosh: mod_bosh
        /captcha: ejabberd_captcha
        /upload: mod_http_upload
        /ws: ejabberd_http_ws
