namespaceOverride: "ejabberd"

statefulSet:
  # -- Number of pods of the statefulSet
  replicas: 3

hosts:
  - xmpp-server.com

listenGlobal:
  # -- c2s top-level listener options:
  #    https://docs.ejabberd.im/admin/configuration/toplevel/#c2s-cafile
  #c2s_ciphers: TLS_CIPHERS
  #c2s_protocol_options: TLS_OPTIONS
  # -- s2s top-level listener options:
  #    https://docs.ejabberd.im/admin/configuration/toplevel/#s2s-access
  #s2s_ciphers: TLS_CIPHERS
  #s2s_protocol_options: TLS_OPTIONS
  s2s_use_starttls: optional

#
# https://docs.ejabberd.im/admin/configuration/toplevel/#acl
#
acl: 
  admin:
    user:
      - "admin@xmpp-server.com"  
# local:
  #   user_regexp: ""
  # loopback:
  #   ip:
  #     - 127.0.0.0/8
  #     - ::1/128

cacert:
  secretName: ca-cert
certFiles:
  # -- Please specify your kubernetes secret containing the tls certificates for
  # the domains specified in .Values.hosts, otherwise the service will not work
  secretName: 
    - xmppserver-cert

elector:
  enabled: true
  createRbac: true
  name: "ejabberd"
  url: "127.0.0.1:4040"

listen:
  http:
    enabled: true
    port: 5280
    expose: true
    exposedPort: 5280
    protocol: TCP
    options:
      ip: "::"
      module: ejabberd_http
      request_handlers: 
        /admin: ejabberd_web_admin

    request_handlers:
      /admin: ejabberd_web_admin
      /api: mod_http_api
      /bosh: mod_bosh
      /captcha: ejabberd_captcha
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
  https:
    enabled: true
    port: 5443
    expose: true
    exposedPort: 5443
    protocol: TCP
    options:
      ip: "::"
      module: ejabberd_http
      tls: true
      request_handlers: 
        /admin: ejabberd_web_admin
        /api: mod_http_api
        /bosh: mod_bosh
        /captcha: ejabberd_captcha
        /upload: mod_http_upload
        /ws: ejabberd_http_ws
