apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - svc.yaml
  - deployment.yaml
  # - svc-oauth2-proxy.yaml
  # - deployment-oauth2-proxy.yaml
  # - ingress-oauth2-proxy.yaml
  - ingress-caddy.yaml

  