---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsmyip
  namespace: whatsmyip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsmyip
  template:
    metadata:
      namespace: whatsmyip
      labels:
        app: whatsmyip
    spec:
      containers:
        - name: whatsmyip
          image: curlimages/curl:8.10.1
          args:
            - "https://api.ipify.org"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
