---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsmyip
  namespace: whatsmyip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsmyip
  template:
    metadata:
      namespace: whatsmyip
      labels:
        app: whatsmyip
    spec:
      containers:
        - name: whatsmyip
          image: yauritux/busybox-curl
          cmd: "/bin/sh"
          args:
            - "-c"
            - "curl -s ipinfo.io/ip; sleep infinity"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
