---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsmyip
  namespace: whatsmyip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsmyip
  template:
    metadata:
      namespace: whatsmyip
      labels:
        app: whatsmyip
    spec:
      initContainers:
        - name: tor
          image: jess/tor-proxy:latest
          restartPolicy: Always
        - name: ping
          image: yauritux/busybox-curl
          command:
            - sh
            - -c
            - |
              while true; do
                IP=`curl --socks5 http://localhost:9050 -L check.torproject.org/api/ip` 
                $IP || break
                echo "Curl failed, retrying in 5 ($IP)"
                sleep 5
              done
              echo "Curl succesfull, exiting ($IP)"
        # - name: vpn
        #   image: qmcgaw/gluetun:v3.36.0
        #   restartPolicy: Always
        #   securityContext:
        #     capabilities:
        #       add:
        #         - NET_ADMIN
        #   env:
        #     - name: VPN_SERVICE_PROVIDER
        #       value: windscribe
        #     - name: VPN_TYPE
        #       value: openvpn
        #     - name: OPENVPN_USER
        #       value: your_user
        #     - name: OPENVPN_PASSWORD
        #       value: your_password
        #     - name: DNS_KEEP_NAMESERVER
        #       value: "on"
        #     - name: FIREWALL_OUTBOUND_SUBNETS
        #       value: "10.42.0.0/15" 
      containers:
        - name: whatsmyip
          image: yauritux/busybox-curl
          command: ["/bin/sh", "-ec", "while :; do echo `curl --socks5 http://localhost:9050 -L ifconfig.me`; echo `curl --socks5 http://localhost:9050 -L check.torproject.org/api/ip`;sleep 5 ; done"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
