---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsmyip
  namespace: whatsmyip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsmyip
  template:
    metadata:
      namespace: whatsmyip
      labels:
        app: whatsmyip
    spec:
      initContainers:
        - name: tor
          image: jess/tor-proxy:latest
          restartPolicy: Always
        - name: ping
          image: busybox
          command:
            - sh
            - -c
            - |
              while ! ping -c 1 8.8.8.8; do
                echo "Ping failed, retrying in 5"
                sleep 5
              done
              echo "ping succesfull, exiting"
      containers:
        - name: whatsmyip
          image: yauritux/busybox-curl
          command: ["/bin/sh", "-ec", "while :; do echo `curl --socks5 http://localhost:9050 -L ifconfig.me`; echo `curl --socks http://localhost:9050  -L https://check.torproject.org/api/ip`;sleep 5 ; done"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
