apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controllers
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/luminosita/k8s-cluster-talos'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'cert-manager'
      server: '*'
    - namespace: 'crossplane'
      server: '*'
    - namespace: 'node-feature-discovery'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
    - namespace: 'sealed-secrets'
      server: '*'
    - namespace: 'gh-actions'
      server: '*'
clusterResourceWhitelist:
    - group: '*'
      kind: '*'
