apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia

configMapGenerator:
  - name: haproxy-kubernetes-ingress
    namespace: haproxy
    literals: 
      - frontend-config-snippet= |
        http-request set-var(txn.scheme) str(https) if { ssl_fc }
        http-request set-var(txn.scheme) str(http) if !{ ssl_fc }

resources:
  - ns.yaml
  - openldap-authelia.yaml

helmCharts:
  - name: authelia
    repo: https://charts.authelia.com
    releaseName: authelia
    namespace: authelia
    version: 0.9.5
    valuesFile: values.yaml
