apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.16.0
    releaseName: "loki"
    namespace: logging
    valuesFile: loki-values.yaml
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.16.6
    releaseName: "promtail"
    namespace: logging
    valuesFile: promtail-values.yaml
