prometheus:
  prometheusSpec:
    nodeSelector:
      topology.kubernetes.io/zone: proxmox
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: proxmox-csi
          volumeName: pv-prometheus
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10G
          selector:
            matchLabels:
              app: prometheus

grafana:
  additionalDataSources: 
    - name: Loki
      type: loki
      url: http://loki-loki-distributed-gateway.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
