prometheus:
  prometheusSpec:
    nodeSelector:
      topology.kubernetes.io/zone: proxmox
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: proxmox-csi
          volumeName: pv-prometheus
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10G
          selector:
            matchLabels:
              app: prometheus
grafana:
  additionalDataSources: 
    - name: Loki
      type: loki
      url: http://loki-gateway.logging/
      access: proxy
      isDefault: false
    - name: Tempo
      type: tempo
      url: http://tempo.tracing:3100/
      access: proxy
      isDefault: false
