apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonatype-registry
  namespace: nexus
  labels:
    app: sonatype-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonatype-registry
  template:
    metadata:
      labels:
        app: sonatype-registry
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 200
        runAsGroup: 200
        fsGroup: 200
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault      
      containers:
        - image: sonatype/nexus3
          name: nexus
      env:
        - name: NEXUS_SECURITY_INITIAL_PASSWORD
          valueFrom: 
            secretKeyRef:
              key: password
              name: sonatype-credentials
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: registry-vol
              mountPath: /nexus-data
      volumes:
        - name: registry-vol
          persistentVolumeClaim:
            claimName: pvc-nexus
