apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - pvc.yaml
  - deployment.yaml
  - svc.yaml
  - http-route.yaml

# helmCharts:
#   - name: nexus-iq-server
#     repo: https://sonatype.github.io/helm3-charts/
#     version: "183.0.0"
#     releaseName: nexus-iq
#     namespace: nexus
#     valuesFile: values.yaml

# patches:
#   - patch: |-
#       $patch: delete
#       apiVersion: v1
#       kind: PersistentVolumeClaim
#       metadata:
#         name: nexus-iq-nexus-iq-server-log
#   - patch: |-
#       $patch: delete
#       apiVersion: v1
#       kind: Pod
#       metadata:
#         name: nexus-iq-test-connection
#   - patch: |-
#       $patch: delete
#       apiVersion: v1
#       kind: Pod
#       metadata:
#         name: nexus-iq-test-check-logs
#   - target:
#       version: v1
#       kind: Deployment
#       name: nexus-iq-nexus-iq-server
#     patch: |-
#       - op: remove
#         path: /spec/template/spec/volumes/1
#       - op: remove
#         path: /spec/template/spec/containers/0/volumeMounts/1
