apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - pvc.yaml

helmCharts:
  - name: nexus-iq-server
    repo: https://sonatype.github.io/helm3-charts/
    version: "183.0.0"
    releaseName: nexus-iq
    namespace: nexus
    valuesFile: values.yaml

patches:
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nexus-iq-nexus-iq-server
        namespace: nexus
      spec:
        template:
          spec:
            containers:
              - name: nexus-iq-server
                volumeMounts:
                  - mountPath: /var/log/nexus-iq-server
                    name: nxiq-pv-log
            volumes:
              - mountPath: /var/log/nexus-iq-server
                name: nxiq-pv-log