apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: single-wikijs
  namespace: wikijs
spec:
  instances: 1
  affinity:
    nodeSelector:
      topology.kubernetes.io/zone: proxmox
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
      additional:
        - selectorType: rw
          updateStrategy: patch
          serviceTemplate:
            metadata:
              name: "single-wikijs-rw"
              labels:
                test-label: "true"
              annotations:
                test-annotation: "true"
            spec:
              type: ClusterIP
  storage:
    size: 1G
    pvcTemplate:
      storageClassName: proxmox-csi
      volumeName: pv-wikijs
      accessModes:
        - ReadWriteOnce
  bootstrap:
    initdb:
      database: wikijs
      owner: wikijs
      # secret:
      #   name: single-wikijs-secret