apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: wikijs
  labels:
    app: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      namespace: wikijs
      labels:
        app: wikijs
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: wikijs
          image: requarks/wiki:latest
#          image: postgres:latest
          # command: ["/bin/sleep"]  # Sleep command to keep the container running
          # args: ["infinity"]           
          env:
          - name: DB_HOST
            value: single-instance-rw.cnpg-database
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                key: port
                name: single-instance-app
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: single-instance-app
          - name: DB_TYPE
            value: postgres
          - name: DB_NAME
            value: wikijs
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: password
                name: single-instance-app
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
          #FIXME
            # requests:
            #   cpu: 50m
            #   memory: 12Mi
            # limits:
            #   cpu: 1000m
            #   memory: 24Mi
