apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wikijs-https
  namespace: wikijs
spec:
  parentRefs:
    - name: internal-production
      namespace: gateway
  hostnames:
    - emisia.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /wiki
      backendRefs:
        - name: wikijs
          port: 80