apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wikijs-https
  namespace: wikijs
spec:
  parentRefs:
    - name: internal
      namespace: gateway
  hostnames:
    - emisia.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /wiki
      filters:
        - type: URLRewrite
          urlRewrite:
            hostname: emisia.net
            path:
              type: ReplaceFullPath
              replaceFullPath: /      
      backendRefs:
        - name: wikijs
          port: 80