apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: redis-operator
    repo: https://spotahome.github.io/redis-operator
    version: 3.3.0
    releaseName: redis-operator
    namespace: redis-operator
