apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
      namespace: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy
        imagePullPolicy: IfNotPresent
        args:
          - --provider=keycloak-oidc
          - --client-id=echo
          - --client-secret=QKroldXvNCfHRjcqlKew6uJkd6gghmvz
          - --proxy-prefix=/oauth2
          - --redirect-url=/oauth2/callback
          - --oidc-issuer-url=https://auth.emisia.net/realms/emisia
          - --email-domain=* # Validate email domain for users, see option documentation
          - --code-challenge-method=S256 # PKCE        
          - --cookie-secret=X
          - --cookie-secure=false
          - --cookie-name=_oauth2_proxy
          - --cookie-expire=24h
          - --set-xauthrequest=true
        # - --http-address=http://:4180
        # - --upstream=file:///dev/null
        # - --provider=XXXXX
        # - --client-id=XXXXX
        # - --client-secret=XXXXX
        # - --proxy-prefix=/oauth2
        # - --redirect-url=/oauth2/callback
        # - --email-domain=*
        # - --cookie-name=_oauth2_proxy
        # - --cookie-secret=XXXXX
        # - --cookie-secure=true
        # - --cookie-expire=24h
        # - --set-xauthrequest=true
        ports:
        - containerPort: 4180
          protocol: TCP
