apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ns.yaml
  - deployment.yaml
  - svc.yaml
  - echoserver.yaml
  - cert-echo-staging.yaml
  - echoserver-ingress.yaml
