apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-openldap
  namespace: blog
spec:
  storageClassName: proxmox-csi
  volumeName: pv-openldap
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
