apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: openldap
spec:
  type: ClusterIP
  selector:
    app: openldap
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: ldap
      port: 389
      targetPort: ldap
