apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secure-ingress
  namespace: authelia
  annotations:
    cert-manager.io/cluster-issuer: "cloudflare-cluster-issuer-production"
spec:
  ingressClassName: haproxy
  tls:
    - secretName: cert-authelia-production
      hosts:
        - authelia.emisia.net   #change to "auth.emisia.net"
  rules:
    - host: authelia.emisia.net   #change to "auth.emisia.net"
      http:
        paths:
          - path: /
            backend:
              service:
                name: authelia
                port: 
                  number: 80
            pathType: Prefix
