apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# configMapGenerator:
#   - name: lua
#     namespace: haproxy
#     files:
#       - http.lua
#       - auth-request.lua
#       - json.lua

resources:
  - ns.yaml

helmCharts:
  - name: haproxy-ingress
    repo: https://haproxy-ingress.github.io/charts
    version: 0.14.7
    releaseName: "haproxy-ingress"
    namespace: haproxy-ingress
    valuesFile: values.yaml
