rbac:
  create: true

controller:
  service:
    externalTrafficPolicy: Local
    type: LoadBalancer
    annotations: 
      io.cilium/lb-ipam-ips: "192.168.50.225" # Static IP Assignment
  metrics:
    enabled: true