apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: haproxy-ingress
    repo: https://haproxy-ingress.github.io/charts
    version: 0.14.8
    releaseName: "haproxy-ingress"
    namespace: haproxy-ingress
    valuesFile: values.yaml
